// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: call.proto

#ifndef PROTOBUF_call_2eproto__INCLUDED
#define PROTOBUF_call_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>
